### ISSUE TITLE
GetResponseEvent became deprecated in Symfony 4.3.

### ISSUE THREAD

**Issue by johanv** [bretrzaun/MaintenanceBundle#5]
The MaintenanceBundle bundle doesn't fully work with Symfony 5.

In Symfony 4.3, `GetResponseEvent` [was renamed as](https://github.com/symfony/symfony/blob/4.4/UPGRADE-4.3.md#httpkernel) `RequestEvent`. `GetResponseEvent` became deprecated, and has disappeared from Symfony 5.

**Comment by bretrzaun** [comment]
Thanks!
